registro/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from registro import views
from registro.views import *
from django.conf import settings


urlpatterns = patterns('',
    url(r'^$', views.List_files.as_view(), name='list_files'),
    url(r'^file$', views.file, name='file'),
    # Definiendo la url que va a servir los archivos/documentos para que puedan ser descargados.
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }),
    # Definiendo la url que va a servir los archivos/documentos para que puedan ser descargados luego de filtrar.
    url(r'^busqueda/media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }),
    url(r'^buscar/$', buscar, name='buscar'),
    url(r'^busqueda/$', busqueda, name='busqueda'),
)

repositorio_documentos/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('registro.urls', namespace='registro')),
]

registro/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.urlresolvers import reverse


class Document(models.Model):
    description = models.CharField(max_length=255, blank=True)
    document = models.FileField(upload_to='')
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.description

registro/forms.py
# -*- coding: utf-8 -*-
from django import forms
from registro.models import Document


class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('description','document',)

registro/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import TemplateView,ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from registro.models import Document
from registro.forms import DocumentForm
from django.shortcuts import render
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.shortcuts import redirect


def file(request):
    """
    Función que permite guardar los documentos, se guardar en /media
    """
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('registro:list_files')
    else:
        form = DocumentForm()
    return render(request, 'registro/file.html', {
        'form': form
    })


class List_files(ListView):
    """
    Clase que permite listar los documentos registrados
    """
    model = Document
    template_name = "registro/list_files.html"


def buscar(request):
    """
    Función que muestra la plantilla con el formulario de búsqueda.
    """
    return render(request, 'registro/buscar.html')


def busqueda(request):
    """
    Función que permite hacer el query con los objetos ya filtrados.
    """
    if 'q' in request.GET and request.GET['q']:
        q = request.GET['q']
        documents = Document.objects.filter(description__icontains=q)
        return render(request, 'registro/buscar.html',  {'documents': documents, 'query': q})
    else:
        return HttpResponse('Por favor introduce un termino de búsqueda.')

registro/templates/registro/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <title>
      {% block titulo %}Base{% endblock %}
    </title>
    {% load staticfiles %}
    <!-- Bootstrap Styles - css
    ================================================== -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link href="{% static 'css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">
    <!-- Styles - css
    ================================================== -->
    <link href="{% static 'css/theme.css" rel="stylesheet">
    <!-- Others - js
    ================================================== -->
    <script src="{% static 'js/ie-emulation-modes-warning.js' %}"></script>
    <script src="{% static 'js/holder.min.js' %}"></script>
    <!-- Jquery - js
    ================================================== -->
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <!-- Bootstrap - js
    ================================================== -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- Bug fix - js
    ================================================== -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
  </head>
  <body>
    
    <!-- Fixed navbar
    ================================================== -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Subir y descargar documentos</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'registro:file' %}">Subir archivo</a></li>
          </ul>
          <ul class="nav navbar-nav">
            <li><a href="{% url 'registro:list_files' %}">Lista de archivos</a></li>
          </ul>
          <ul class="nav navbar-nav">
            <li><a href="{% url 'registro:buscar' %}">Buscar</a></li>
          </ul>
        </div>
      </div>
    </nav><!-- End navbar -->

    <br />
    <br />
    <br />

    <div class="container theme-showcase" role="main">
      <div class="well">
      {% block cuerpo %}
      {% endblock %}
      </div>
    </div> <!-- /container -->

  </body>
</html>

registro/templates/registro/buscar.html
{% extends "registro/base.html" %}
{% block titulo %}File{% endblock %}
{% block cuerpo %}
<h3>Buscar documento por la descripción</h3>
<form action="/busqueda/" method="get">
  <input type="text" name="q">
  <input type="submit" value="Buscar">
</form>
{% if documents %}
<p>Estas buscado: <strong>{{ query }}</strong></p>
  <p>Documentos encontrados: {{ documents|length }} documentos.</p>
  <table border="1px" cellpadding="0px" cellspacing="0px" style="width:100%">
    <thead>
      <tr>
        <th><b>ID</b></th>
        <th><b>Descripción</b></th>      
        <th><b>Fecha de subida</b></th>
        <th><b>Ubicación electróica</b></th>
      </tr>
    </thead>
    {% for x in documents %}
    <tbody>
      <tr>
        <td>
          {{ x.id }}
        </td>
        <td>
          {{ x.description }}
        </td>
        <td>
          {{ x.uploaded_at}}
        </td>
        <td>
          <a href="media/{{ x.document}}">{{ x.document}}</a>
        </td>
      </tr>
    </tbody>
    {% endfor %}
  </table>
{% else %}
  <p>Ningún documento coincide con el criterio de búsqueda.</p>
{% endif %}
{% endblock %}

registro/templates/registro/file.html
{% extends "registro/base.html" %}
{% block titulo %}File{% endblock %}
{% block cuerpo %}
<form method="post" enctype="multipart/form-data">{% csrf_token %}

  <label>{{ form.document.label }}:</label>
  {{ form.document }}

  <hr />

  <label>{{ form.description.label }}:</label>
  {{ form.description }}

  <hr />

  <button type="submit">Upload</button>
</form>
{% endblock %}

registro/templates/registro/list_files.html
{% extends "registro/base.html" %}
{% block titulo %}List of Files{% endblock %}
{% block cuerpo %}
<h1>Lista de documentos</h1>
<br />
<table border="1px" cellpadding="0px" cellspacing="0px" style="width:100%">
  <thead>
    <tr>
      <th><b>ID</b></th>
      <th><b>Descripción</b></th>      
      <th><b>Fecha de subida</b></th>
      <th><b>Ubicación electróica</b></th>
    </tr>
  </thead>
  {% for x in object_list %}
  <tbody>
    <tr>
      <td>
        {{ x.id }}
      </td>
      <td>
        {{ x.description }}
      </td>
      <td>
        {{ x.uploaded_at}}
      </td>
      <td>
        <a href="media/{{ x.document}}">{{ x.document}}</a>
      </td>
    </tr>
  </tbody>
  {% endfor %}
</table>
{% endblock %}